### ISSUE TITLE
Changing the keychain password is not supported

### ISSUE THREAD

**Issue by kindlyseth** [pda/aws-keychain#20]
Changing passwords is sometimes required. Frequently, it's recommended even when not required.

Here's how to do it manually:

```
USER=sk # substitute your username
# a relative path doesn't work
security set-keychain-password /Users/"$USER"/Library/Keychains/aws-keychain.keychain
```

**Comment by pda** [comment]
Note also the keychain can be added to and managed by the `Keychain Access.app` utility that ships with macOS. No new features coming in aws-keychain; see https://github.com/99designs/aws-vault instead.
