### ISSUE TITLE
aws-keyhcain rm breaks the app

### ISSUE THREAD

**Issue by rickw** [pda/aws-keychain#23]
I did an `aws-keychain rm x` but then a subsequent `ls` lists it as still being there though using it generates the migrate message. There are no files in my user Library keychains directory but if I tried to add the item again I get `security: SecKeychainCreate /Users/rick/Library/Keychains/aws-keychain.keychain: A keychain with the same name already exists`

This is macOS Sierra.

**Comment by pda** [comment]
Odd. Perhaps `$HOME/.aws/aws-keychain.list` is out of sync with actual Keychain data? Doesn't quite explain the user Library keychains directory being empty yet seeing that error.

I'd suggest moving to https://github.com/99designs/aws-vault — aws-keychain isn't maintained anymore.

**Comment by rickw** [comment]
Thanks, I figured something changed in the Security framework.
